---
- name: Install packages
  community.general.pkgng:
    name:
      - git-lite
      - elixir
      - gmake
      - cmake
      - ImageMagick7
      - ffmpeg
      - p5-Image-ExifTool

- name: setup pleroma service user
  ansible.builtin.user:
    name: pleroma
    create_home: true

- name: Git checkout
  become: true
  become_user: pleroma
  ansible.builtin.git:
    repo: 'https://git.pleroma.social/pleroma/pleroma.git'
    dest: /usr/home/pleroma/pleroma
    version: stable

- name: install hex
  become: true
  become_user: pleroma
  ansible.builtin.command:
    cmd: "mix local.hex --force"
    chdir: /usr/home/pleroma/pleroma
    creates: /home/pleroma/.mix/archives/hex-2.0.0
  environment: "{{ pleroma_env }}"

- name: install mix deps
  become: true
  become_user: pleroma
  ansible.builtin.command:
    cmd: "mix deps.get --force"
    chdir: /usr/home/pleroma/pleroma
    # creates: /home/pleroma/pleroma/config/generated_config.exs
  environment: "{{ pleroma_env }}"

- name: copy startup script
  ansible.builtin.copy:
    src: pleroma.service
    dest: /usr/local/etc/rc.d/pleroma
    mode: '0755'
    
- name: enable pleroma
  community.general.sysrc:
    name: pleroma_enable
    value: "YES"

- name: Ensure pleroma is started at boot time
  ansible.builtin.service:
    name: pleroma
    state: started

- name: Print info
  ansible.builtin.debug:
    msg: |
      
      Almost done! now ssh into {{ ansible_ssh_host }} and follow the instructions in the README